### PR TITLE
Update SNI for some Amazoned sites

### PR DESCRIPTION
**Pull request by ygsk10**
https://github.com/URenko/Accesser/issues/19#issuecomment-479494082

### CODE REVIEW

**Comment by URenko** [comment]
Well... I need some tests.
As I know, CDNs like cloudfront use SNI to determine sites, so a wrong SNI may lead to trouble. But it seems that one subdomain of cloudfront is bound to one site?

**Comment by ygsk10** [comment]
Yes. It's bound to one site.
For CloudFront, cname as SNI is possible, and the response content is OK

**Comment by ygsk10** [comment]
https://github.com/SeaHOH/GotoX/wiki/如何使用伪造-SNI-的功能

**Comment by ygsk10** [comment]
To test, run command like

`curl -v https://d11c2xcc0ucqv1.cloudfront.net -H "Host: blog.nicovideo.jp"`

`curl -v https://d2c1o7y4lmdvf6.cloudfront.net -H "Host: info.nicovideo.jp`

`curl -v https://d4fsvsnk8os9s.cloudfront.net -H "Host: site.nicovideo.jp"`

**Comment by URenko** [comment]
It works well. Thanks!

**Pull request merged**
